version: 2
updates:
- package-ecosystem: pip
  directory: "/datanommer.models/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  allow:
  - dependency-type: all
- package-ecosystem: pip
  directory: "/datanommer.commands/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  allow:
  - dependency-type: all
- package-ecosystem: pip
  directory: "/datanommer.consumer/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  allow:
  - dependency-type: all
