queue_rules:
  - name: default
    queue_conditions:
      - label!=no-mergify
      - -draft
      - approved-reviews-by=@fedora-infra/data-team
      - "#changes-requested-reviews-by=0"
      - check-success=Checks
      - check-success=Licenses (models)
      - check-success=Licenses (consumer)
      - check-success=Licenses (commands)
      - check-success=Unit tests (3.10, models)
      - check-success=Unit tests (3.10, consumer)
      - check-success=Unit tests (3.10, commands)
      - check-success=Unit tests (3.11, models)
      - check-success=Unit tests (3.11, consumer)
      - check-success=Unit tests (3.11, commands)
    merge_method: rebase

pull_request_rules:
  - name: Merge on approval
    conditions: []
    actions:
      queue:
