---
- name: Install RPM packages
  dnf:
      name:
      - fedora-messaging
      - gcc
      - git
      - poetry
      - python3-devel
      - python3-pip
      - vim
      - krb5-devel
      - libpq-devel
      - tox
      - python-psycopg2
      state: present

- name: Install the .bashrc
  copy:
    src: .bashrc
    dest: /home/vagrant/.bashrc
    mode: 0644
    owner: vagrant
    group: vagrant

- name: Create a directory for the virtualenv
  file:
    name: /srv/venv
    state: directory
    mode: 0755
    owner: vagrant
    group: vagrant

- name: Create the virtualenv and install poetry
  pip:
    name: poetry
    virtualenv: /srv/venv
  become: yes
  become_user: vagrant

- name: Install datanommer.models with poetry
  shell: /srv/venv/bin/poetry install
  args:
    chdir: /home/vagrant/datanommer/datanommer.models/
  become: yes
  become_user: vagrant

- name: Install datanommer.commands with poetry
  shell: /srv/venv/bin/poetry install
  args:
    chdir: /home/vagrant/datanommer/datanommer.commands/
  become: yes
  become_user: vagrant

- name: Install datanommer.consumer with poetry
  shell: /srv/venv/bin/poetry install
  args:
    chdir: /home/vagrant/datanommer/datanommer.consumer/
  become: yes
  become_user: vagrant

- name: Use the stage fedora-messaging queue to consume
  copy:
    remote_src: True
    src: /etc/fedora-messaging/fedora.stg.toml
    dest: /etc/fedora-messaging/config.toml


- name: configure datanommer_sqlalchemy_url in fedora-messaging config
  lineinfile:
    path: /etc/fedora-messaging/config.toml
    regexp: "example_key = \"for my consumer\""
    line: "datanommer_sqlalchemy_url = \"postgresql://datanommer:datanommer@localhost/messages\""

- name: Create datanommer db
  shell: /srv/venv/bin/poetry run datanommer-create-db
  args:
    chdir: /home/vagrant/datanommer/datanommer.commands
  become: yes
  become_user: vagrant


- name: Install the systemd unit files for datanommer consumer
  copy:
      src: "datanommer.service"
      dest: /etc/systemd/system/datanommer.service
      mode: 0644
  

- name: Start datanommer service using systemd
  systemd:
    state: started
    name: datanommer
    daemon_reload: yes
    enabled: yes
