name: Auto-approve Dependabot PRs
on:
  schedule:
    - cron: "7 * * * *"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-approve:
    name: Auto-approve minor and patch updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: koj-co/dependabot-pr-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          approve-minor: true
          approve-patch: true

